import { NextResponse, type NextRequest } from "next/server";

const US_COUNTRY_CODES = new Set(["US", "UM"]);

// Social media crawlers that must bypass geo-redirect so OG tags are visible.
const CRAWLER_UA_RE =
  /twitterbot|facebookexternalhit|linkedinbot|slackbot|discordbot|whatsapp|telegrambot|applebot|googlebot|bingbot|pinterestbot|embedly|vkshare|w3c_validator/i;

function getCountryCode(req: NextRequest) {
  const raw =
    req.headers.get("x-vercel-ip-country") ??
    req.headers.get("cf-ipcountry") ??
    "";
  return raw.toUpperCase();
}

// OG image paths generated by Next.js — must always be reachable.
function isOgImagePath(pathname: string) {
  return (
    pathname.endsWith("/opengraph-image") ||
    pathname.endsWith("/twitter-image") ||
    pathname === "/og-image" ||
    pathname === "/icon" ||
    pathname === "/apple-icon"
  );
}

export function middleware(req: NextRequest) {
  const { pathname, search } = req.nextUrl;

  // Skip internal and static files.
  if (
    pathname.startsWith("/_next") ||
    pathname.startsWith("/api") ||
    pathname.startsWith("/favicon") ||
    pathname.startsWith("/wallet-error-guard.js")
  ) {
    return NextResponse.next();
  }

  // Never geo-redirect OG image routes or social media crawlers.
  const ua = req.headers.get("user-agent") ?? "";
  if (isOgImagePath(pathname) || CRAWLER_UA_RE.test(ua)) {
    return NextResponse.next();
  }

  const referralMatch = pathname.match(/^\/r\/([^/]+)$/i);
  const referralCode = referralMatch
    ? decodeURIComponent(referralMatch[1] ?? "").toLowerCase()
    : null;

  const country = getCountryCode(req);
  if (!US_COUNTRY_CODES.has(country)) {
    const res = NextResponse.next();
    if (referralCode) {
      res.cookies.set("blink_ref", referralCode, {
        maxAge: 60 * 60 * 24 * 30,
        path: "/",
        sameSite: "lax",
      });
    }
    return res;
  }

  const redirectUrl = new URL("https://blink.us");
  redirectUrl.searchParams.set("notice", "us-restriction");
  redirectUrl.searchParams.set("from", pathname + search);
  const res = NextResponse.redirect(redirectUrl, 307);
  if (referralCode) {
    res.cookies.set("blink_ref", referralCode, {
      maxAge: 60 * 60 * 24 * 30,
      path: "/",
      sameSite: "lax",
    });
  }
  return res;
}

export const config = {
  matcher: ["/((?!.*\\..*).*)"],
};
