import {
  type SearchGroup,
  type SearchIndexItem,
} from "@/lib/internal-search-types";

/** Build a searchable index row (shared by static shortcuts + server index). */
export function searchItem(
  id: string,
  group: SearchGroup,
  title: string,
  subtitle: string | undefined,
  href: string,
  keywords: Array<string | null | undefined> = [],
): SearchIndexItem {
  const clean = keywords.filter(Boolean) as string[];
  return {
    id,
    group,
    title,
    subtitle,
    href,
    value: [title, subtitle, ...clean].filter(Boolean).join(" ").toLowerCase(),
  };
}

/** Instant page shortcuts — always available before datasets load. */
export const SEARCH_PAGES: SearchIndexItem[] = [
  searchItem("page-home", "pages", "Home", "Today · revenue & traffic", "/internal", [
    "home",
    "today",
    "dashboard",
    "overview",
  ]),
  searchItem(
    "page-products",
    "pages",
    "Products",
    "Plan catalog & MRR",
    "/internal/products",
    ["products", "plans", "catalog", "pricing"],
  ),
  searchItem(
    "page-checkout",
    "pages",
    "Checkout links",
    "Claim URLs & custom prices",
    "/internal/checkout-links",
    ["checkout", "claim", "links", "invoice"],
  ),
  searchItem(
    "page-memberships",
    "pages",
    "Memberships",
    "Active Stripe members",
    "/internal/memberships",
    ["memberships", "subscribers", "members", "trial"],
  ),
  searchItem(
    "page-people",
    "pages",
    "People",
    "Fingerprints, enrichment, CRM",
    "/internal/people",
    ["people", "visitors", "fingerprint", "crm", "enrichment"],
  ),
  searchItem("page-leads", "pages", "Leads", "Pipeline board", "/internal/leads", [
    "leads",
    "pipeline",
    "prospects",
    "crm",
  ]),
  searchItem(
    "page-store",
    "pages",
    "Store",
    "Shopify storefront overview",
    "/internal/store",
    [
      "store",
      "shopify",
      "storefront",
      "merch",
      "internet culture",
      "account.rokitg",
    ],
  ),
  searchItem(
    "page-store-submissions",
    "pages",
    "Store · Submissions",
    "Shopify Forms captures",
    "/internal/store/submissions",
    ["submissions", "forms", "shopify forms", "leads"],
  ),
  searchItem(
    "page-store-customers",
    "pages",
    "Store · Customers",
    "Shopify customers linked to forms",
    "/internal/store/customers",
    ["customers", "shopify customers"],
  ),
  searchItem(
    "page-store-orders",
    "pages",
    "Store · Orders",
    "Shopify recent orders",
    "/internal/store/orders",
    ["orders", "shopify orders"],
  ),
  searchItem(
    "page-store-payments",
    "pages",
    "Store · Payments",
    "Shopify payment transactions",
    "/internal/store/payments",
    ["shopify payments", "gateways"],
  ),
  searchItem(
    "page-store-products",
    "pages",
    "Store · Products",
    "Shopify catalog",
    "/internal/store/products",
    ["shopify products", "catalog", "inventory"],
  ),
  searchItem(
    "page-earnings",
    "pages",
    "Earnings",
    "Gross volume & forecast",
    "/internal/earnings",
    ["earnings", "revenue", "gross", "mrr", "forecast", "lifetime"],
  ),
  searchItem(
    "page-earnings-referrals",
    "pages",
    "Earnings · Referrals",
    "Propr attributed volume & commission",
    "/internal/earnings",
    [
      "propr",
      "referrals",
      "affiliate",
      "commission",
      "ROKIT",
      "partner volume",
      "sync",
      "api.propr.xyz",
    ],
  ),
  searchItem(
    "page-payments",
    "pages",
    "Payments",
    "Stripe + Whop history",
    "/internal/payments",
    ["payments", "invoices", "stripe", "whop", "charges"],
  ),
  searchItem(
    "page-crypto",
    "pages",
    "Crypto",
    "On-chain USDC pays",
    "/internal/crypto",
    ["crypto", "usdc", "wallet", "onchain"],
  ),
  searchItem(
    "page-stats",
    "pages",
    "Stats",
    "Marketing board",
    "/internal/stats",
    ["stats", "marketing", "conversion", "kpi"],
  ),
  searchItem(
    "page-funnel",
    "pages",
    "Funnel",
    "Emails · visitor → paid conversion",
    "/internal/funnel",
    [
      "funnel",
      "email",
      "waitlist",
      "capture",
      "conversion",
      "visitor",
      "paid",
    ],
  ),
  searchItem(
    "page-emails",
    "pages",
    "Emails",
    "Audience intelligence · campaigns · sends",
    "/internal/emails",
    [
      "emails",
      "resend",
      "campaign",
      "audience",
      "blast",
      "whop",
      "migration",
      "newsletter",
      "propr",
      "automation",
    ],
  ),
  searchItem(
    "page-traffic",
    "pages",
    "Traffic",
    "Live + Cloudflare history",
    "/internal/traffic",
    [
      "traffic",
      "impressions",
      "pageviews",
      "uniques",
      "cloudflare",
      "map",
    ],
  ),
  searchItem(
    "page-affiliates",
    "pages",
    "Affiliates",
    "Referral partners & commissions",
    "/internal/affiliates",
    ["affiliate", "referral", "partner", "commission", "ref"],
  ),
  searchItem(
    "page-promos",
    "pages",
    "Promo codes",
    "Discounts & coupons",
    "/internal/promos",
    ["promo", "coupon", "discount", "codes"],
  ),
];

/** Instant action shortcuts — create flows & deep links. */
export const SEARCH_ACTIONS: SearchIndexItem[] = [
  searchItem(
    "action-create-membership",
    "actions",
    "Add membership",
    "Comp / trial Stripe member",
    "/internal/memberships#create",
    ["add", "create", "membership", "comp", "trial", "grant"],
  ),
  searchItem(
    "action-create-checkout",
    "actions",
    "Create checkout link",
    "Custom-price claim URL",
    "/internal/checkout-links#create",
    ["create", "checkout", "claim", "link", "invoice"],
  ),
  searchItem(
    "action-leads",
    "actions",
    "Open leads board",
    "Capture & manage prospects",
    "/internal/leads",
    ["create", "lead", "prospect", "pipeline"],
  ),
  searchItem(
    "action-funnel",
    "actions",
    "Open email funnel",
    "Landing captures & conversion rates",
    "/internal/funnel",
    ["funnel", "email", "waitlist", "conversion"],
  ),
  searchItem(
    "action-create-affiliate",
    "actions",
    "Create affiliate",
    "Referral code & share link",
    "/internal/affiliates#create",
    ["create", "affiliate", "referral", "partner", "commission"],
  ),
  searchItem(
    "action-people-visitors",
    "actions",
    "Fingerprinted visitors",
    "People · Visitors tab",
    "/internal/people?tab=visitors",
    ["visitors", "fingerprint", "people"],
  ),
  searchItem(
    "action-people-leads",
    "actions",
    "People · Leads",
    "Conversion pipeline in People",
    "/internal/people?tab=leads",
    ["people", "leads", "crm", "pipeline"],
  ),
  searchItem(
    "action-people-members",
    "actions",
    "People · Members",
    "Paying member profiles",
    "/internal/people?tab=members",
    ["people", "members", "paid"],
  ),
  searchItem(
    "action-sync-whop-people",
    "actions",
    "Sync Whop people",
    "Enrich People from Whop export",
    "/internal/people?tab=leads",
    ["whop", "sync", "import", "people", "enrich"],
  ),
];

/** Client seed for ⌘K — pages + actions shown before datasets finish loading. */
export const SEARCH_SHORTCUTS: SearchIndexItem[] = [
  ...SEARCH_PAGES,
  ...SEARCH_ACTIONS,
];
