export type BreakpointKey = "xl" | "lg" | "md" | "sm" | "xs" | "xxs";

export type GridItem = {
  i: string;
  x: number;
  y: number;
  w: number;
  h: number;
  moved?: boolean;
  static?: boolean;
  isDraggable?: boolean;
  isResizable?: boolean;
  minW?: number;
  maxW?: number;
  minH?: number;
  maxH?: number;
};

export type BreakpointLayouts = Record<BreakpointKey, GridItem[]>;

export const breakpoints: Record<BreakpointKey, number> = {
  xl: 1600,
  lg: 1200,
  md: 996,
  sm: 768,
  xs: 480,
  xxs: 0,
};

export const cols: Record<BreakpointKey, number> = {
  xl: 48,
  lg: 48,
  md: 36,
  sm: 8,
  xs: 4,
  xxs: 2,
};

export const layouts: BreakpointLayouts = {
  xl: [
    {
      w: 29,
      h: 4,
      x: 0,
      y: 0,
      i: "watchlist",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 29,
      h: 6,
      x: 0,
      y: 0,
      i: "marketInfoHeader",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 29,
      h: 30,
      x: 0,
      y: 4,
      i: "tradingChart",
      moved: false,
      static: false,
      isDraggable: false,
      isResizable: true,
    },
    {
      w: 10,
      h: 40,
      x: 38,
      y: 0,
      i: "orderForm",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 38,
      h: 29,
      x: 0,
      y: 59,
      i: "openOrders",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 9,
      h: 40,
      x: 29,
      y: 0,
      i: "orderBookTradeHistory",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 10,
      h: 29,
      x: 38,
      y: 54,
      i: "accountInfo",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  lg: [
    {
      w: 48,
      h: 4,
      x: 0,
      y: 0,
      i: "watchlist",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 36,
      h: 5,
      x: 0,
      y: 4,
      i: "marketInfoHeader",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 26,
      h: 51,
      x: 0,
      y: 9,
      i: "tradingChart",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 12,
      h: 56,
      x: 36,
      y: 4,
      i: "orderForm",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 34,
      h: 28,
      x: 0,
      y: 60,
      i: "openOrders",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 10,
      h: 51,
      x: 26,
      y: 9,
      i: "orderBookTradeHistory",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 14,
      h: 28,
      x: 34,
      y: 60,
      i: "accountInfo",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  md: [
    {
      w: 36,
      h: 4,
      x: 0,
      y: 0,
      i: "watchlist",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 36,
      h: 5,
      x: 0,
      y: 4,
      i: "marketInfoHeader",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 24,
      h: 32,
      x: 0,
      y: 9,
      i: "tradingChart",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 12,
      h: 62,
      x: 24,
      y: 9,
      i: "orderForm",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 36,
      h: 24,
      x: 0,
      y: 71,
      i: "openOrders",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 12,
      h: 30,
      x: 0,
      y: 41,
      i: "orderBookTradeHistory",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 12,
      h: 30,
      x: 12,
      y: 41,
      i: "accountInfo",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  sm: [
    {
      w: 8,
      h: 4,
      x: 0,
      y: 0,
      i: "watchlist",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 8,
      h: 5,
      x: 0,
      y: 4,
      i: "marketInfoHeader",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 8,
      h: 30,
      x: 0,
      y: 9,
      i: "tradingChart",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 63,
      x: 4,
      y: 39,
      i: "orderForm",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 8,
      h: 40,
      x: 0,
      y: 102,
      i: "openOrders",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 35,
      x: 0,
      y: 39,
      i: "orderBookTradeHistory",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 28,
      x: 0,
      y: 74,
      i: "accountInfo",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  xs: [
    {
      w: 4,
      h: 4,
      x: 0,
      y: 0,
      i: "watchlist",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 5,
      x: 0,
      y: 2,
      i: "marketInfoHeader",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 30,
      x: 0,
      y: 9,
      i: "tradingChart",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 48,
      x: 0,
      y: 39,
      i: "orderForm",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 4,
      h: 30,
      x: 0,
      y: 119,
      i: "openOrders",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
    {
      w: 1,
      h: 1,
      x: 0,
      y: 149,
      i: "orderBookTradeHistory",
      moved: false,
      static: false,
    },
    {
      w: 4,
      h: 32,
      x: 0,
      y: 87,
      i: "accountInfo",
      moved: false,
      static: false,
      isDraggable: true,
      isResizable: true,
    },
  ],
  xxs: [],
};
